title: overtrue - 安正超博客
name: overtrue
email: anzhengchao@gmail.com
description: 安正超，网名overtrue，PHP工程师，从事web相关的开发工作。开源爱好者，GitHub:https://github.com/overtrue。
keywords: Laravel,Laravel教程,Laravel安装,Laravel视频,安正超,overtrue,Pinyin,汉字转拼音
skill_keywords: [PHP, Javascript, HTML+CSS, Linux, Laravel, Git, Mac, RESTful, Stackoverflow, Sublime Text, OmniGaffale, OminiPlan]

timezone:    PRC
encoding: "utf-8"

url: http://overtrue.me
baseurl:  "/"
domain:    overtrue.me
permalink:     /articles/:year/:month/:title.html
paginate_path: 'page:num'
paginate:   10
source_code: https://github.com/overtrue/overtrue.github.io

# Build settings
markdown:    kramdown
highlighter: rouge
excerpt_separator: ""

kramdown:
  input: GFM
  enable_coderay: true

# coderay:
#   coderay_wrap: div
#   coderay_line_numbers: nil
#   coderay_tab_width: 4
#   coderay_bold_every: 10
#   coderay_css: class

gems:
  - jemoji
  # - rouge
  # # - jekyll-mentions
  - jekyll-sitemap
  - jekyll-html-pipeline

disqus:
  id: overtrueme

google:
    analytics_id: UA-55452630-1

# navigation
navs:
  -
    href: /
    label: Home

  -
    href: /open-source.html
    label: Open-Source

  -
    href: https://github.com/overtrue
    label: GitHub
    target: _blank

  -
    href: http://weibo.com/44294631
    label: Weibo
    target: _blank

  -
    href: /about
    label: About

popular_repos: ['pinyin', 'wechat', 'writor', 'laravel-wechat', 'laravel-lang', 'laravel-pinyin', 'latest-laravel', 'latest-lumen']
contribute_repos: ['laravel/framework', 'tymondesigns/jwt-auth', 'caouecs/Laravel-lang']